version: "3.8"
name: "axum-server"
services:
  postgres:
    container_name: ax-postgres-dev
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      # - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U postgres -d postgres'"
        ]
      interval: 20s
      timeout: 5s
      retries: 5
    networks:
      - axum-network

  minio:
    container_name: ax_minio_s3
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-volume:/data
    restart: unless-stopped
    networks:
      - axum-network

volumes:
  postgres-volume:
    driver: local
  minio-volume:
    driver: local

networks:
  axum-network:
    driver: bridge