-- Base app schema

CREATE TABLE "user"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
    user_name     VARCHAR(256) NOT NULL UNIQUE,
    user_password VARCHAR(256),
    password_salt uuid         NOT NULL DEFAULT gen_random_uuid(),
    token_salt    uuid         NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE "task"
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    title VARCHAR(256) NOT NULL
);

CREATE TABLE "project"
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    title   VARCHAR(256) NOT NULL,
    content TEXT         NOT NULL
);

CREATE TABLE "tags"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    name       VARCHAR(85),
    project_id BIGINT NOT NULL,
    CONSTRAINT project_id_fk
        FOREIGN KEY (project_id)
            REFERENCES project (id)
            ON DELETE CASCADE
);

CREATE TABLE "roadmap"
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    project_id           BIGINT NOT NULL UNIQUE,
    stage_id             INT    NOT NULL,
    completed_by         INT    NOT NULL DEFAULT 0,
    estimated_completion date            DEFAULT CURRENT_DATE,
    create_at            timestamp       DEFAULT CURRENT_TIMESTAMP,
    update_at            timestamp       DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "stages"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT         NOT NULL
)